client/urls.py
"""

SPDX-License-Identifier: AGPL-3.0-or-later
Copyright (C) 2025 Andrew Knotek <arknotek@pm.me>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""


from django.urls import path

from . import views

app_name = 'client'

urlpatterns = [
    path('all/', views.client_index, name="client_index"),
    path('inactive/', views.client_inactive, name='client_inactive'),
    path('me/', views.me_index, name='me_index'),
    path('<int:client_id>/', views.client_edit, name='client_edit'),
    path('new/', views.client_edit, name='client_new'),

    path("caseworker_login/", views.caseworker_login, name="caseworker_login"),

    path("set_active/<int:client_id>/", views.client_set_active, name="client_set_active"),
    path("set_inactive/<int:client_id>/", views.client_set_inactive, name="client_set_inactive"),

    # These are the tab menu items on the client screen
    path("client_settings/<int:client_id>/", views.client_settings_index, name="client_settings_index"),

    path("emr_episodes/<int:client_id>/", views.emr_episode_edit, name="emr_episodes_index"),
    path("emr_episodes/<int:client_id>/<int:episode_id>/", views.emr_episode_edit, name="emr_episodes_edit"),
    # Build an EMR Episode view where only the episode is ID (it can redirect to the one above here)

    path("emr_episodes/<int:client_id>/<int:episode_id>/form/<int:form_type_id>/", views.emr_episode_edit, name="emr_episode_form_list"),
    path("emr_episodes/<int:client_id>/<int:episode_id>/form/<str:note_type_id>/", views.emr_episode_edit, name="emr_episode_note_list"),
    path("emr_episodes/<int:client_id>/<int:episode_id>/doc/<int:doc_type_id>/", views.emr_episode_edit, name="emr_episode_doc_list"),

    path("new_emr_episode/<str:episode_type>/<int:client_id>/", views.new_emr_episode, name="new_emr_episode"),

    path("emr_form/<int:form_type_id>/<int:episode_id>/", views.emr_form_edit, name="emr_form_new"),
    path("emr_form/<int:emr_form_id>/", views.emr_form_edit, name="emr_form_edit"),
    path("emr_form/<int:emr_form_id>/sign/", views.emr_form_sign, name="emr_form_sign"),
    path("emr_form/<int:emr_form_id>/unlock/", views.emr_form_unlock, name="emr_form_sign"),
    path("emr_form_history/<int:emr_form_id>/", views.emr_form_history, name="emr_form_history"),

    path("emr_form/<int:emr_form_id>/supervisor_sign/", views.emr_form_supervisor_sign, name="emr_form_supervisor_sign"),
    path("emr_form/<int:emr_form_id>/electronic_signature/", views.emrform_electric_sig, name="emr_form_electronic_sig_new"),
    path("emr_form/<int:emr_form_id>/electronic_signature/<int:emrform_sig_id>/", views.emrform_electric_sig, name="emr_form_electronic_sig_edit"),

    path("emr_doc/<int:doc_type_id>/<int:episode_id>/", views.emr_doc_edit, name="emr_doc_new"),
    path("emr_doc/<int:emr_doc_id>/", views.emr_doc_edit, name="emr_doc_edit"),
    path("emr_doc/<int:emr_doc_id>/emr_docs/<int:emr_doc_id2>/<str:filename>", views.emr_doc_file, name="emr_doc_file"),
    path("emr_doc/<int:emr_doc_id>/emr_docs/<int:emr_doc_id2>/<str:filename>/", views.emr_doc_file, name="emr_doc_file"),
    path("emr_doc/<int:emr_doc_id>/file/", views.emr_doc_file, name="emr_doc_file_short"),
    path("emr_doc/<int:emr_doc_id>/view/", views.emr_doc_view, name="emr_doc_view"),
    path("emr_doc/<int:emr_doc_id>/<int:emr_form_id>/unlink/", views.emr_doc_unlink, name="emr_doc_unlink"),

    path("emr_casenote/reopen/<int:emr_casenote_id>/", views.emr_casenote_reopen, name="emr_casenote_reopen"),

    path("emr_message/", views.emr_message_edit, name="emr_message_new"),
    path("emr_message/<int:message_id>/", views.emr_message_edit, name="emr_message_edit"),

    path("pps_episodes/<int:client_id>/", views.pps_episodes_index, name="pps_episodes_index"),
    path("case_notes_index/<int:client_id>/", views.case_notes_index, name="case_notes"),
    path("state_forms/<int:client_id>/", views.state_forms_index, name="state_forms_index"),

    path('address/<int:address_id>/', views.address_edit, name="address_edit"),
    path('address/new/', views.address_edit, name="address_new"),

    path('contact/<int:contact_id>/', views.contact_edit, name="contact_edit"),
    path('contact/new/', views.contact_edit, name="contact_new"),

    path('insurance/<int:insurance_id>/', views.insurance_edit, name="insurance_edit"),
    path('insurance/', views.insurance_edit, name="insurance_new"),

    path('assigned_staff/<int:assigned_staff_id>/', views.assigned_staff_edit, name='assigned_staff_edit'),
    path('assigned_staff/', views.assigned_staff_edit, name='assigned_staff_new'),

    path('casenote/<int:casenote_id>/', views.casenote_edit, name="casenote_edit"),
    path('casenote/new/', views.casenote_edit, name="casenote_new"),

    path("casenote_file/<int:file_id>/casenote_files/<int:user_id>/<int:client_id>/<str:filename>", views.casenote_files),
    path("casenote_file/<int:file_id>/casenote_files/<int:user_id>/<int:client_id>/<str:filename>/", views.casenote_files),
    path('casenote_file/<int:casenote_file_id>/', views.casenote_file, name='casenote_file'),
    path('casenote_file/new/', views.casenote_file, name='casenote_file_new'),

    path("casenote/view_all/<int:client_id>/", views.casenote_view_all, name="casenote_view_all"),

    path("casenote/reopen/<int:casenote_id>/", views.casenote_reopen, name="casenote_reopen"),

    path("legal_name/<int:client_id>/<int:legal_name_id>/", views.legal_name_edit, name="legal_name"),
    path("legal_name/<int:client_id>/new/", views.legal_name_edit, name="legal_name_new"),


    path("sacwis/import_mgmt/", views.sacwis_import_mgmt, name="sacwis_import_mgmt"),
    path("sacwis/import_mgmt/<int:sac_row_id>/", views.sacwis_import_edit, name="sacwis_import_edit"),

    # The PPS episodes are not currently in use
    #path("pps_epi_sort/<uuid>/", views.pps_epi_sort, name="pps_epi_sort"),

    #path('pps_aoda_epi/<int:pk>/', views.pps_aoda_edit, name='pps_aoda_epi_edit'),
    #path('pps_aoda_epi/new/', views.pps_aoda_edit, name='pps_aoda_epi_new'),

    #path('pps_mh_epi/<int:pk>/', views.pps_mh_edit, name='pps_mh_epi_edit'),
    #path('pps_mh_epi/new/', views.pps_mh_edit, name='pps_mh_epi_new'),

    #path('pps_core_epi/<int:pk>/', views.pps_core_edit, name='pps_core_epi_edit'),
    #path('pps_core_epi/new/', views.pps_core_edit, name='pps_mh_core_epi_new'),

    #path('pps_b3_epi/<int:pk>/', views.pps_b3_edit, name='pps_b3_epi_edit'),
    #path('pps_b3_epi/new/', views.pps_b3_edit, name='pps_mh_b3_epi_new'),


    path("atp/<int:pk>/", views.atp_edit, name="atp_edit"),
    path("atp/new/", views.atp_edit, name="atp_new"),



    path('form/<name>/', views.form_download, name='form_download'),

    path("ajax_duplicate_name_detect/", views.ajax_duplicate_name_detect, name="duplicate_name_detect"),
    path("ajax_calculate_units/<int:emr_form_id>/<int:minutes>/", views.ajax_calculate_units, name="ajax_calculate_minutes"),



]

nova/urls.py
"""nova URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
import views

admin.site.site_header = 'NOVA Administration'

handler404 = views.handler404
handler403 = views.handler403
handler500 = views.handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('silk/', include('silk.urls', namespace='silk')),
    re_path(r'^login/', auth_views.LoginView.as_view(), name='login'),
    path('', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logged_out.html', next_page=None), name='logout'),
    path('logged_out/', auth_views.LogoutView.as_view(template_name="logged_out.html", next_page=None), name="logged_out"),
    re_path(r'^loginsort/', views.loginSort, name="Login Sort"),
    re_path(r'^LoginSort/', views.loginSort, name="Login Sort"),  # For some reason our login is leading us to this capitalized re_path. still need to figure out why
    re_path(r'^thanks/', views.thanks, name="Thanks"),

    path('client/', include('client.urls')),
    path('accounting/', include('accounting.urls')),
    path('config/', include('config.urls')),
    path('report/', include('report.urls')),
    path('external/', include('external.urls')),
    path('sacwis/', include('sacwis.urls')),

    #path("script.js", views.script_view, name="script_view"),

    #path("ajax_get_session_time/", views.ajax_get_session_time, name="ajax_get_session_time"),

    path("test500/", views.test500, name="test500"),
    path("testnotify/<str:message>/<int:user_id>/", views.testnotify, name="testnotify"),

    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),

    path("license", TemplateView.as_view(template_name="LICENSE", content_type="text/plain")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sacwis/urls.py
from django.urls import path

from . import views


app_name = 'sacwis'

urlpatterns = [
    path("check_write/", views.sac_check_write_index, name="sac_check_write_index"),
    path("check_write/<int:check_write_id>/", views.sac_check_write_dtl, name="sac_check_write_dtl"),

    path("person_index/", views.person_index, name="person_index"),
    path("person/<int:person_id>/", views.person_dtl, name="person_dtl"),
    path("sacperson/<int:sacid>/", views.sacperson_dtl, name="sacperson_dtl"),


    path("link_to_client_mgmt/<int:person_id>/", views.link_repl_person_to_client_mgmt, name="link_to_client_mgmt"),
    path("sac_link_to_client_mgmt/<int:sacid>/", views.sac_link_repl_person_to_client_mgmt, name="sac_link_to_client_mgmt"),

    path("link_repl_to_client/", views.link_repl_to_client, name="link_repl_to_client"),
    path("unlink_repl_from_client/", views.unlink_repl_from_client, name="unlink_repl_from_client"),
    path("create_client_from_repl/", views.create_client_from_repl, name="create_client_from_repl"),

    # This whole link to vendor needs to be reworked completely...
    # for now, I think we can update the existing vendor view to match
    # the proper pagination/filter format as the rest of the app then copy
    # that view to here and pre-fill the filter fields etc..
    # May be able to modify these existing views, may be less work... im
    # not flipping sure... all we really need to do is match the provider id
    # to a vendor.. I think that can be done..
    # will need to provide further provider information so now im not sure
    # exactly how to transmit the data... holy shit we can just link in the damn
    # check write line!!
    # All of these functions need to be modified but it shouldn't be so bad...
    path("link_to_vendor_mgmt/<int:sac_check_write_line_id>/", views.link_sac_provider_id_to_vendor_mgmt, name="link_to_vendor_mgmt"),
    path("link_sac_provider_id_to_vendor/", views.link_sac_provider_id_to_vendor, name="link_sac_provider_id_to_vendor"),
    path("unlink_sac_provider_id_from_vendor/", views.unlink_sac_provider_id_from_vendor, name="unlink_sac_provider_id_from_vendor"),
    path("create_vendor_from_sac_checkline/", views.create_vendor_from_sac_checkline, name="create_vendor_from_sac_checkline"),

    path("service_type/", views.service_type_index, name="service_type_index"),
    path("service_type/<int:service_type_id>/", views.service_type_dtl, name="service_type_dtl"),
    path("link_service_type/", views.link_service_type, name="link_service_type"),
    path("unlink_service_type/", views.unlink_service_type, name="unlink_service_type"),
    path("create_service_from_repl/", views.create_service_from_repl, name="create_service_from_repl"),
    path("sacservicetype_dtl/<str:service_type_code>/", views.sacservicetype_dtl, name="sacservicetype_dtl"),

    path("nova_service/<int:nova_service_id>/", views.nova_service_edit, name="nova_service_edit"),

]

templates/sacwis/link_sac_provider_id_to_vendor_mgmt.html
{% extends 'base.html' %}
{% load nova_tags %}

{% block breadcrumb %}
    <div class='breadcrumb'>
        <div class='container'>
            <a href="{% url 'sacwis:sac_check_write_index' %}">Check Files</a>
            <a href="{% url 'sacwis:sac_check_write_dtl' check_write_id=instance.saccheckwritefile.id %}">{{instance.saccheckwritefile}}</a>
            {{title}}
        </div>
    </div>
{% endblock %}

{% block content %}
<div class='container print-hide'>
    <div class="row justify-content-left margin-top-2">
        <div class="col-md-12">
            <h2>{{title}}</h2>
            {% if not vendor %}
                <p>
                    The eWiSACWIS Provider ID ({{instance.provider_id}}) is not currently linked to a Nova Vendor.
                </p>
                <form name="frm-create-vendor-from-sac-provider-{{item.id}}" method="post" action="{% url 'sacwis:create_vendor_from_sac_checkline'  %}"  class="list-form">
                    {% csrf_token %}
                    <input type="hidden" name="sac_check_line_id" value="{{instance.id}}" />
                    <input type="hidden" name="sac_provider_name" value="{{instance.payee_name}}" />
                    <input type="button" onclick='createVendorFromReplModal(this)' class="btn btn-secondary btn-sm" value="Create Nova vendor" />
                </form>
            {% else %}
                <form name="frm-unlink-provider-id-from-vendor-{{item.id}}" method="post" action="{% url 'sacwis:unlink_sac_provider_id_from_vendor' %}"  class="list-form">
                    {% csrf_token %}
                    <input type="hidden" name="sac_check_line_id" value="{{instance.id}}" />
                    <input type="hidden" name="sac_provider_name" value="{{instance.payee_name}}" />
                    <input type="hidden" name="nova_vendor_id" value="{{vendor.id}}" />
                    <input type="hidden" name="nova_vendor_name" value="{{vendor.name}}" />
                    <input type="button" onclick='unlinkProviderIdVendorModal(this)' class="btn btn-secondary btn-sm" value="Remove Link" />
                </form>
            {% endif %}


            <table class="listview-table-no-order-no-search mt-4" style="font-size:1.25rem">
                <thead>
                    <tr>
                        <th></th>
                        <th>Name</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><span class="cell"><strong>eWiSACWIS</strong></span></td>
                        <td><span class="cell">{{instance.payee_name|default:''}}</span></td>
                        <td><span class="cell"><strong></strong></span></td>
                    </tr>

                    <tr>
                        <td><span class="cell"><strong>Nova</strong></span></td>
                        {% if vendor %}
                            <td><span class="cell">{{vendor}}</span></td>
                            <td><a href="{% url 'config:vendor_edit' pk=vendor.id %}">Go to Nova Vendor</a></td>
                        {% else %}
                            <td><span class="cell">----------</span></td>
                            <td><span class="cell">----------</span></td>
                            <td><span class="cell"></span></td>
                        {% endif %}
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<hr>
{% if not vendor %}
    <div class='container'>
        <div class="row justify-content-left margin-top-2">
            <div class="col-md-12">
                <h4>Nova Vendor Lookup</h4>
                <form id="frm" method="post" action="">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {% include "form_buttons.html" with filter=True %}
                </form>
            </div>
        </div>
    </div>

    {% if page %}
        <div class='container'>
            <div class="row margin-top-1">
                <div class='col-12'>
                    <table class="listview-table-no-order-no-search">
                        <thead>
                            <tr>
                                <th>Nova ID</th>
                                <th>Name</th>
                                <th>Number</th>
                                <th>City</th>
                                <th>Street</th>
                                <th>Notes</th>
                                <th>Linked</th>
                                <th class="center">Link</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in page %}
                            <tr>
                                <td><span class="cell">{{item.id}}</span></td>
                                <td><span class="cell">{{item.name}}</span></td>
                                <td><span class="cell">{{item.vendor_number}}</span></td>
                                <td><span class="cell">{{item.city|default:''}}</span></td>
                                <td><span class="cell">{{item.street|default:''}}</span></td>
                                <td><span class="cell">{{item.notes|default:''}}</span></td>
                                <td><span class="cell">{% if item.sacperson %}Yes ({{item.sacperson.id}} - {{item.sacperson.payee_name}}){% else %}No{% endif %}</span></td>
                                 <td class="center"><span class="">
                                    <form name="frm-link-repl-to-vendor-{{item.id}}" method="post" action="{% url 'sacwis:link_sac_provider_id_to_vendor' %}"  class="list-form">
                                        {% csrf_token %}
                                        <input type="hidden" name="sac_check_line_id" value="{{instance.id}}" />
                                        <input type="hidden" name="nova_vendor_id" value="{{item.id}}" />
                                        <input type="hidden" name="nova_vendor_name" value="{{item.name}}" />
                                        <input type="hidden" name="sac_provider_name" value="{{instance.payee_name}}" />
                                        <input type="button" onclick='linkPersonVendorModal(this)' class="btn btn-secondary btn-sm" value="Link" />
                                    </form>
                                </span></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% include 'page_controls.html' %}
                </div>
            </div>
        </div>
    {% else %}
        <div class="container">
            <div class="row margin-top-2">
                <div class="col-md-12 center">
                    <hr>
                    <h4>No results found</h4>
                </div>
            </div>
        </div>
    {% endif %}
{% endif %}




{%endblock%}

{% block page_javascript %}
<script>
function linkPersonVendorModal(ele) {
    // Depending on if this repl person is already linked, display a message
    // asking the user to confirm their decision
    let newVendorName = ele.form.elements["nova_vendor_name"].value;
    let newVendorId = ele.form.elements["nova_vendor_id"].value;

    {% if vendor %}
        let msg = `eWiSACWIS Person <strong>{{instance.payee_name}}</strong> is already linked to Nova Vendor <strong>{{vendor.name}} ({{vendor.id}})</strong>.
<br><br>Performing this action will remove the existing link and replace it with Nova Vendor <strong>${newVendorName} (${newVendorId})</strong>.
Please confirm you action to continue.`
    {% else %}
        let msg = `Are you sure you would like to link Nova Vendor <strong>${newVendorName} (${newVendorId})</strong> with eWiSACWIS Person <strong>{{instance.payee_name}}</strong>? Please confirm your action to continue.`
    {% endif %}

    showModal(
        titleText="Confirm REPL to Nova Link",
        bodyText=msg,
        primaryText="Confirm Link",
        secondaryText="Cancel",
        primaryAction=function(){ele.form.submit();},
        secondaryAction=hideModal,
        opacity=1,
        loadAction=null,
        customHtml=null,
    );
}


function unlinkProviderIdVendorModal(ele) {
    // Confirm that the user wants to remove the link betweent he REPL person
    // and the Nova Vendor
    let newVendorName = ele.form.elements["nova_vendor_name"].value;
    let newVendorId = ele.form.elements["nova_vendor_id"].value;

    let msg = `
        Are you sure you would like to remove the link between eWiSACWIS Person
        <strong>{{instance.payee_name}}</strong> and Nova Vendor
        <strong>${newVendorName} (${newVendorId})</strong>?
    `

    showModal(
        titleText="Confirm Unlink",
        bodyText=msg,
        primaryText="Remove Link",
        secondaryText="Cancel",
        primaryAction=function(){ele.form.submit();},
        secondaryAction=hideModal,
        opacity=1,
        loadAction=null,
        customHtml=null,
    );
}



function createVendorFromReplModal(ele) {
    // Confirm that the user wants to remove the link betweent he REPL person
    // and the Nova Vendor

    let msg = `
        <p>
            <u><strong>This should be used only if a matching vendor does not
            exist in Nova.</u></strong>
        </p>
        <p>
            Create a <strong>New Nova Vendor</strong> from the information available on
            the eWiSACWIS Person <strong>{{instance.payee_name}}</strong>. Are you sure?
        </p>

    `

    showModal(
        titleText="Confirm Create",
        bodyText=msg,
        primaryText="Create Nova Vendor",
        secondaryText="Cancel",
        primaryAction=function(){ele.form.submit();},
        secondaryAction=hideModal,
        opacity=1,
        loadAction=null,
        customHtml=null,
    );
}

</script>
{% endblock %}

templates/sacwis/sac_check_write_index.html
{% extends 'base.html' %}
{% load nova_tags %}
{% block content %}
<div class='container'>
    <div class='row margin-top-2'>
        <div class="col-md-12">
            <h2>
                eWiSACWIS Check Write Files
            </h2>
        </div>
    </div>

    <div class="row margin-top-1">
        <div class='col-12'>
            <table class="listview-table-no-search" data-order='[[1, "asc"]]'>
                <thead>
                    <tr>
                        <th>Status</th>
                        <th>Date</th>
                        <th>Filename</th>
                        <th>Lines</th>
                    </tr>
                </thead>
                {% if check_data %}
                <tbody>
                    {% for item in check_data %}
                    <tr>
                        <td><a href="{% url 'sacwis:sac_check_write_dtl' check_write_id=item.id %}">{{item.get_status}}</a></td>
                        <td><a href="{% url 'sacwis:sac_check_write_dtl' check_write_id=item.id %}">{{item.created_at|list_date}}</a></td>
                        <td><a href="{% url 'sacwis:sac_check_write_dtl' check_write_id=item.id %}">{{item.filename}}</a></td>
                        <td><a href="{% url 'sacwis:sac_check_write_dtl' check_write_id=item.id %}">{{item.get_line_count}}</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
                {% endif %}
            </table>
        </div>
    </div>

</div>
{%endblock%}

templates/sacwis/sac_person_dtl.html
{% extends 'base.html' %}
{% load nova_tags %}
{% block breadcrumb %}
    <div class='breadcrumb'>
        <div class='container'>
            <a href="{% url 'sacwis:person_index' %}">All Persons</a>
            {{instance}}
        </div>
    </div>
{% endblock %}

{% block content %}
<div class='container'>
    <div class='row margin-top-2'>
        <div class="col-md-12">
            <h3>{{instance}}</h3>
            <hr>
        </div>
        <div class="col-md-12">
            {% if instance.nova_client %}
                Linked to Nova Client:
                <a href="{% url 'client:client_edit' client_id=instance.nova_client.id  %}">
                    '{{instance.nova_client}}'
                </a>
                <a class="btn btn-sm btn-secondary ml-4" href="{% url 'sacwis:link_to_client_mgmt' person_id=instance.id %}">Manage Link</a>
            {% else %}
                Not linked to a Nova Client.
                <a class="btn btn-sm btn-secondary ml-4" href="{% url 'sacwis:link_to_client_mgmt' person_id=instance.id %}">Link to Nova Client</a>

            {% endif %}

        </div>
    </div>
</div>

{% if instance.get_family %}
    <div class="container">
        <div class="row margin-top-2">
            <div class="col-md-12">
                <h4>Family</h4>
                <table class='listview-table-no-order-no-search'>
                    <thead>
                        <tr>
                            <th>Relationship</th>
                            <th>Person</th>
                            <th>Nova Link</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for key, value in instance.get_family.items %}
                            <tr>
                                <td><span class="cell">{{key}}</span></td>
                                <td><a href="{% url 'sacwis:person_dtl' person_id=value.id %}">{{value}}</a></td>
                                <td>
                                    {% if value.nova_client %}
                                        <a href="{% url 'client:client_edit' client_id=value.nova_client.id %}">{{value}}</a>
                                    {% else %}
                                        <span class="cell">Not linked</span>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endif %}

<div class="container">
    <div class="row margin-top-2">
        <div class="col-md-12">
            <h4>Episodes</h4>
        </div>
    </div>

     <div class="row margin-top-1">
        <div class="col-12">
            <table class="listview-table-no-order-no-search" data-order='[[ 0, "asc" ]]'>
                <thead>
                    <tr>
                        <th>Start</th>
                        <th>End</th>
                        <th>Service Type</th>
                        <th>SPC Code</th>
                        <th>Target Group</th>
                        <th>Nova Service</th>
                    </tr>
                </thead>
                <tbody>
                    {% for episode in instance.sacepisode_set.all %}
                        <tr>
                            <td><span class="cell">{{episode.start|list_date|default:''}}</span></td>
                            <td><span class="cell">{{episode.end|list_date|default:''}}</span></td>
                            <td>
                                {% if episode.sacservicetype %}
                                    <a href="{% url 'sacwis:service_type_dtl' service_type_id=episode.sacservicetype.id %}">{{episode.sacservicetype}}</a>
                                {% endif %}
                            </td>
                            <td><span class="cell">{{episode.sacservicetype.spc_code|default:''}}</span></td>
                            <td><span class="cell">{{episode.target_group}}</span></td>
                            <td><span class="cell">{{episode.sacservicetype.nova_service|default:'Not linked'}}</span></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


<div class="container">
    <div class="row margin-top-2">
        <div class="col-md-12">
            <h4>Transactions</h4>
        </div>
    </div>

     <div class="row margin-top-1">
        <div class="col-12">
            <table class="listview-table-no-order-no-search" data-order='[[ 0, "asc" ]]'>
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Fiscal Year</th>
                        <th>Fiscal Period</th>
                        <th>Amount</th>
                        <th>Description</th>
                        <th>Nova Service</th>
                        <th>Nova Auth</th>
                    </tr>
                </thead>
                <tbody>
                    {% for transaction in person_transactions %}
                        <tr>
                            <td><span class="cell"></span></td>
                            <td><span class="cell"></span></td>
                            <td><span class="cell"></span></td>
                            <td><span class="cell"></span></td>
                            <td><span class="cell"></span></td>
                            <td><span class="cell"></span></td>
                            <td><span class="cell"></span></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{%endblock%}