accounting/urls.py
"""

SPDX-License-Identifier: AGPL-3.0-or-later
Copyright (C) 2025 Andrew Knotek <arknotek@pm.me>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""


from django.urls import path
from django.views.generic.base import RedirectView, TemplateView
from . import views

app_name = 'accounting'

urlpatterns = [
    #path('', RedirectView.as_view(url='/loginsort', permanent=False), name='accounting_index'),
    path('', views.accounting_index, name='accounting_index'),

    path('account/', views.account_index, name='account_index'),
    path('account/<int:pk>/', views.account_edit, name='account_edit'),
    path('account/new/', views.account_edit, name='account_new'),

    # "Auth" is the new (2024-08-06) authorization system. The paths and views
    # for 'authorization' exist as an interface for working with authorizations
    # within the confines of contracts. These auths have their own views
    # coming from the auth list view.
    # The users' goal is to deprecate the existing authorizations, so hopefully
    # that will happen soon.
    path("auth/", views.auth_index, name="auth_index"),
    path("auth/<int:auth_id>/", views.auth_edit, name="auth_edit"),
    path("auth/new/", views.auth_new, name="auth_new"),
    path("auth/<int:auth_id>/reopen/", views.auth_reopen, name="auth_reopen"),
    path("auth_file/new/<int:auth_id>/", views.auth_file_edit, name="auth_file_new"),
    path("auth_file/<int:auth_file_id>/", views.auth_file_edit, name="auth_file_edit"),
    path("auth_file/<int:auth_file_id>/auth_files/<int:auth_file_id2>/<str:filename>", views.auth_file_file, name="auth_file_file"),
    path("auth_file/<int:auth_file_id>/auth_files/<int:auth_file_id2>/<str:filename>/", views.auth_file_file, name="auth_file_file"),
    path("auth_file/<int:auth_file_id>/file/", views.auth_file_file, name="auth_file_file_short"),
    path("auth_file/<int:auth_file_id>/view/", views.auth_file_view, name="auth_file_view"),

    #path("authorization/", views.authorization_index, name="authorization_index"),
    path("authorization/<int:pk>/", views.authorization_edit, name="authorization_edit"),
    path("authorization/new/", views.authorization_edit, name="authorization_new"),

    path('budget/', views.budget_index, name='budget_index'),
    path('budget/<int:pk>/', views.budget_edit, name='budget_edit'),
    path('budget/new/', views.budget_edit, name='budget_new'),
    path("budget/copy_existing/", views.budget_copy_existing, name="budget_copy_existing"),

    path('budget_item/<int:pk>/', views.budget_item_edit, name='budget_item_edit'),
    path('budget_item/new/', views.budget_item_edit, name='budget_item_new'),
    #path('budgetitem/<int:pk>', RedirectView.as_view(pattern_name='accounting:budget_item_edit', query_string=True)),

    path('contract/', views.contract_index, name='contract_index'),
    path('contract/all/', views.contract_index_all, name='contract_index_all'),
    path('contract/<int:pk>/', views.contract_edit, name='contract_edit'),
    path('contract/new/', views.contract_edit, name='contract_new'),

    path("contract_service/<int:contract_id>/add/", views.contract_service_edit, name="contract_service_new"),
    path("contract_service/<int:contract_id>/<int:contract_service_id>/", views.contract_service_edit, name="contract_service_edit"),


    path('funding_profile/', views.funding_profile_index, name='funding_profile_index'),
    path('funding_profile/<int:pk>/', views.funding_profile_edit, name='funding_profile_edit'),
    path('funding_profile/new/', views.funding_profile_edit, name='funding_profile_new'),

    path('lot/', views.lot_index, name='lot_index'),
    path('lot/<int:pk>/', views.lot_edit, name='lot_edit'),
    path('lot/new/', views.lot_edit, name='lot_edit_new'),
    path("lot/all/", views.lot_index_all, name="lot_index_all"),

    path('rate/', views.rate_index, name='rate_index'),
    path('rate/<int:pk>/', views.rate_edit, name='rate_edit'),
    path('rate/new/', views.rate_edit, name='rate_edit'),

    path('transaction/', views.transaction_index, name='transaction_index'),
    path('transaction/<int:pk>/', views.transaction_edit, name='transaction_edit'),
    path('transaction/new/', views.transaction_edit, name='transaction_new'),
    path('transaction/<int:pk>/unlink/', views.transaction_unlink, name="transaction_unlink"),

    path("transaction_file/new/<int:transaction_id>/", views.transaction_file_edit, name="transaction_file_new"),
    path("transaction_file/<int:transaction_file_id>/", views.transaction_file_edit, name="transaction_file_edit"),
    path("transaction_file/<int:transaction_file_id>/transaction_files/<int:transaction_file_id2>/<str:filename>", views.transaction_file_file, name="transaction_file_file"),
    path("transaction_file/<int:transaction_file_id>/transaction_files/<int:transaction_file_id2>/<str:filename>/", views.transaction_file_file, name="transaction_file_file"),
    path("transaction_file/<int:transaction_file_id>/file/", views.transaction_file_file, name="transaction_file_file_short"),
    path("transaction_file/<int:transaction_file_id>/view/", views.transaction_file_view, name="transaction_file_view"),

    path("payroll_transaction/new/", views.payroll_transaction_edit, name="payroll_transaction_new"),
    path("payroll_transaction/<int:pk>/", views.payroll_transaction_edit, name="payroll_transaction_edit"),

    path("client_payment/new/", views.client_payment_edit, name="client_payment_edit"),
    path("client_payment/<int:pk>/", views.client_payment_edit, name="client_payment_edit"),

    path('journal_entry/', views.journal_entry_index, name='journal_entry_index'),
    path("journal_entry/all/", views.journal_entry_index_all, name="journal_entry_index_all"),
    path('journal_entry/<int:pk>/', views.journal_entry_edit, name='journal_entry_edit'),
    path('journal_entry/new/', views.journal_entry_edit, name='journal_entry_new'),
    path('journal_entry/verify/', views.journal_entry_verify, name='journal_entry_verify'),
    path('journal_entry/<int:pk>/unlink_all/', views.journal_entry_unlink_all, name="journal_entry_unlink_all"),
    path("journal_entry/<int:pk>/export/", views.journal_entry_export, name="journal_entry_export"),
    path("journal_entry/unverify/<int:pk>/", views.journal_entry_unverify, name="journal_entry_unverify"),
    path("journal_entry/review/<int:journal_id>/", views.journal_entry_review, name="journal_entry_review"),

    path("journal_file/new/<int:journal_id>/", views.journal_file_edit, name="journal_file_new"),
    path("journal_file/<int:journal_file_id>/", views.journal_file_edit, name="journal_file_edit"),
    path("journal_file/<int:journal_file_id>/journal_files/<int:journal_file_id2>/<str:filename>", views.journal_file_file, name="journal_file_file"),
    path("journal_file/<int:journal_file_id>/journal_files/<int:journal_file_id2>/<str:filename>/", views.journal_file_file, name="journal_file_file"),
    path("journal_file/<int:journal_file_id>/file/", views.journal_file_file, name="journal_file_file_short"),
    path("journal_file/<int:journal_file_id>/view/", views.journal_file_view, name="journal_file_view"),

    path('journal_trans/<int:pk>/', views.journal_trans_edit, name='journal_edit'),
    path('journal_trans/new/', views.journal_trans_edit, name='journal_new'),

    path("payroll/", views.payroll_dist_index, name="payroll_dist_index"),
    path("payroll/<int:pk>/", views.payroll_dist_edit, name="payroll_dist_edit"),
    path("payroll/new/", views.payroll_dist_edit, name="payroll_dist_new"),

    path("payroll_je/<int:pk>/", views.payroll_je_edit, name="payroll_je_edit"),
    path("payroll_je/new/<int:parent_id>/<int:employee_id>/<int:_amount>/", views.payroll_je_edit, name="payroll_je_new"),

    path("atp_discharge/", views.atp_discharge, name="atp_discharge"),
]

nova/urls.py
"""nova URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
import views

admin.site.site_header = 'NOVA Administration'

handler404 = views.handler404
handler403 = views.handler403
handler500 = views.handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('silk/', include('silk.urls', namespace='silk')),
    re_path(r'^login/', auth_views.LoginView.as_view(), name='login'),
    path('', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logged_out.html', next_page=None), name='logout'),
    path('logged_out/', auth_views.LogoutView.as_view(template_name="logged_out.html", next_page=None), name="logged_out"),
    re_path(r'^loginsort/', views.loginSort, name="Login Sort"),
    re_path(r'^LoginSort/', views.loginSort, name="Login Sort"),  # For some reason our login is leading us to this capitalized re_path. still need to figure out why
    re_path(r'^thanks/', views.thanks, name="Thanks"),

    path('client/', include('client.urls')),
    path('accounting/', include('accounting.urls')),
    path('config/', include('config.urls')),
    path('report/', include('report.urls')),
    path('external/', include('external.urls')),
    path('sacwis/', include('sacwis.urls')),

    #path("script.js", views.script_view, name="script_view"),

    #path("ajax_get_session_time/", views.ajax_get_session_time, name="ajax_get_session_time"),

    path("test500/", views.test500, name="test500"),
    path("testnotify/<str:message>/<int:user_id>/", views.testnotify, name="testnotify"),

    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),

    path("license", TemplateView.as_view(template_name="LICENSE", content_type="text/plain")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sacwis/urls.py
from django.urls import path

from . import views


app_name = 'sacwis'

urlpatterns = [
    path("check_write/", views.sac_check_write_index, name="sac_check_write_index"),
    path("check_write/<int:check_write_id>/", views.sac_check_write_dtl, name="sac_check_write_dtl"),

    path("person_index/", views.person_index, name="person_index"),
    path("person/<int:person_id>/", views.person_dtl, name="person_dtl"),
    path("sacperson/<int:sacid>/", views.sacperson_dtl, name="sacperson_dtl"),


    path("link_to_client_mgmt/<int:person_id>/", views.link_repl_person_to_client_mgmt, name="link_to_client_mgmt"),
    path("sac_link_to_client_mgmt/<int:sacid>/", views.sac_link_repl_person_to_client_mgmt, name="sac_link_to_client_mgmt"),

    path("link_repl_to_client/", views.link_repl_to_client, name="link_repl_to_client"),
    path("unlink_repl_from_client/", views.unlink_repl_from_client, name="unlink_repl_from_client"),
    path("create_client_from_repl/", views.create_client_from_repl, name="create_client_from_repl"),

    # This whole link to vendor needs to be reworked completely...
    # for now, I think we can update the existing vendor view to match
    # the proper pagination/filter format as the rest of the app then copy
    # that view to here and pre-fill the filter fields etc..
    # May be able to modify these existing views, may be less work... im
    # not flipping sure... all we really need to do is match the provider id
    # to a vendor.. I think that can be done..
    # will need to provide further provider information so now im not sure
    # exactly how to transmit the data... holy shit we can just link in the damn
    # check write line!!
    # All of these functions need to be modified but it shouldn't be so bad...
    path("link_to_vendor_mgmt/<int:sac_check_write_line_id>/", views.link_sac_provider_id_to_vendor_mgmt, name="link_to_vendor_mgmt"),
    path("link_sac_provider_id_to_vendor/", views.link_sac_provider_id_to_vendor, name="link_sac_provider_id_to_vendor"),
    path("unlink_sac_provider_id_from_vendor/", views.unlink_sac_provider_id_from_vendor, name="unlink_sac_provider_id_from_vendor"),
    path("create_vendor_from_sac_checkline/", views.create_vendor_from_sac_checkline, name="create_vendor_from_sac_checkline"),

    path("service_type/", views.service_type_index, name="service_type_index"),
    path("service_type/<int:service_type_id>/", views.service_type_dtl, name="service_type_dtl"),
    path("link_service_type/", views.link_service_type, name="link_service_type"),
    path("unlink_service_type/", views.unlink_service_type, name="unlink_service_type"),
    path("create_service_from_repl/", views.create_service_from_repl, name="create_service_from_repl"),
    path("sacservicetype_dtl/<str:service_type_code>/", views.sacservicetype_dtl, name="sacservicetype_dtl"),

    path("nova_service/<int:nova_service_id>/", views.nova_service_edit, name="nova_service_edit"),

]

templates/accounting/account_edit.html
<!--

SPDX-License-Identifier: AGPL-3.0-or-later
Copyright (C) 2025 Andrew Knotek <arknotek@pm.me>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

-->


<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}
<div class='container{% if popup%}-fluid{%endif%}'>
<div class="row">
	<div class="col-12">
		<h3>{{ title }}</h3>
        {% if subtitle and not popup %}
        <h5>{{subtitle}}</h5>
        {%endif%}
		<form id="frm" method="post" action="">
            {% if popup %}<input type='hidden' name='popup' value='true' />{%endif%}
			{% csrf_token %}
			{{ form.as_p }}
			{% include "form_buttons.html" %}
		</form>
	</div>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

</div>
{%endblock%}

templates/accounting/auth_new.html
<!--

SPDX-License-Identifier: AGPL-3.0-or-later
Copyright (C) 2025 Andrew Knotek <arknotek@pm.me>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

-->


{% extends 'base.html' %}
{% block content %}

{% if not popup %}
<div class='breadcrumb print-hide'>
    <div class='container'>
        <a href="{% url 'accounting:auth_index' %}">Authorization</a>
        {% if instance %}{{instance}}
        {% else %}New Authorization
        {%endif%}
    </div>
</div>
{% endif %}



<div class='container{% if popup%}-fluid{%endif%}'>
    <div class="row">
        <div class="col-12">
            <h3>{{ title }}</h3>
            {% if subtitle and not popup %}
                <h5>{{subtitle}}</h5>
            {%endif%}
            <form id="frm" method="post" action="">
                {% if popup %}<input type='hidden' name='popup' value='true' />{%endif%}
                {% csrf_token %}

                <div class="form-section">
                    <p class="w20">
                        {{ form.auth_date_from.label_tag }}
                        {{ form.auth_date_from }}
                    </p>

                    <p class="w20">
                        {{ form.auth_date_to.label_tag }}
                        {{ form.auth_date_to }}
                    </p>

                    <p class="w20">
                        {{ form.auth_week.label_tag }}
                        {{ form.auth_week }}
                    </p>

                    <p class="w50 clear-left">
                        {{ form.auth_caseworker.label_tag }}
                        {{ form.auth_caseworker }}
                    </p>

                    <p class="w50">
                        {{ form.auth_client_lookup.label_tag }}
                        {{ form.auth_client_lookup }}
                        {{ form.auth_client }}
                    </p>

                    <p class="w50">
                        {{ form.auth_account_lookup.label_tag }}
                        {{ form.auth_account_lookup }}
                        {{ form.auth_account }}
                    </p>

                    <p class="w50">
                        {{ form.auth_vendor_lookup.label_tag }}
                        {{ form.auth_vendor_lookup }}
                        {{ form.auth_vendor }}
                    </p>


                    <p class="w20">
                        {{ form.auth_service_date_from.label_tag }}
                        {{ form.auth_service_date_from }}
                    </p>

                    <p class="w20">
                        {{ form.auth_service_date_to.label_tag }}
                        {{ form.auth_service_date_to }}
                    </p>

                    <p class="w20">
                        {{ form.auth_service_lookup.label_tag }}
                        {{ form.auth_service_lookup }}
                        {{ form.auth_service }}
                    </p>

                    <p class="w15">
                        {{ form.auth_amount.label_tag }}
                        {{ form.auth_amount }}
                    </p>

                    <p class="w15">
                        {{ form.auth_unit_type.label_tag }}
                        {{ form.auth_unit_type }}
                    </p>

                    <p class="w10">
                        {{ form.auth_units.label_tag }}
                        {{ form.auth_units }}
                    </p>





                    <p class="w16 clear-left">
                        {{ form.auth_target_group.label_tag }}
                        {{ form.auth_target_group }}
                    </p>

                    <p class="w16">
                        {{ form.auth_wic_cat.label_tag }}
                        {{ form.auth_wic_cat }}
                    </p>

                    <p class="w16">
                        {{ form.auth_iii_b_cat.label_tag }}
                        {{ form.auth_iii_b_cat }}
                    </p>

                    <p class="w16">
                        {{ form.auth_iii_e_cat.label_tag }}
                        {{ form.auth_iii_e_cat }}
                    </p>

                    <p class="w16">
                        {{ form.auth_cst_cat.label_tag }}
                        {{ form.auth_cst_cat }}
                    </p>

                    <p class="w16">
                        {{ form.auth_elder_abuse_cat.label_tag }}
                        {{ form.auth_elder_abuse_cat }}
                    </p>

                    <p class="w100">
                        {{ form.auth_notes.label_tag }}
                        {{ form.auth_notes }}
                    </p>


                </div>


                {% if not instance or not instance.id %}
                    <div class="form-section">
                        <h4>Client</h4>
                        <hr>

                        <p class="w25">
                            {{ form.client_last_name.label_tag }}
                            {{ form.client_last_name }}
                        </p>

                        <p class="w25">
                            {{ form.client_first_name.label_tag }}
                            {{ form.client_first_name }}
                        </p>

                        <p class="w20">
                            {{ form.client_middle_name.label_tag }}
                            {{ form.client_middle_name }}
                        </p>

                        <p class="w15">
                            {{ form.client_birthdate.label_tag }}
                            {{ form.client_birthdate }}
                        </p>

                        <p class="w15">
                            {{ form.client_gender.label_tag }}
                            {{ form.client_gender }}
                        </p>
                    </div>

                    {% comment %}
                    <div class="form-section">
                        <h4>Vendor</h4>
                        <hr>

                        <p class="w25">
                            {{ form.ven_etf_payment.label_tag }}
                            {{ form.ven_etf_payment }}
                        </p>

                        <p class="w50">
                            {{ form.ven_name.label_tag }}
                            {{ form.ven_name }}
                        </p>

                        <p class="w25">
                            {{ form.ven_vendor_number.label_tag }}
                            {{ form.ven_vendor_number }}
                        </p>



                        <p class="w25 clear-left">
                            {{ form.ven_street.label_tag }}
                            {{ form.ven_street }}
                        </p>

                        <p class="w15">
                            {{ form.ven_suite.label_tag }}
                            {{ form.ven_suite }}
                        </p>

                        <p class="w30">
                            {{ form.ven_city.label_tag }}
                            {{ form.ven_city }}
                        </p>

                        <p class="w15">
                            {{ form.ven_state.label_tag }}
                            {{ form.ven_state }}
                        </p>

                        <p class="w15">
                            {{ form.ven_zip.label_tag }}
                            {{ form.ven_zip }}
                        </p>
                    </div>
                    {% endcomment %}
                {% endif %}


                {% include "form_buttons.html" %}
            </form>
        </div>
    </div>
</div>
{%endblock%}


{% block page_javascript %}
<script>
    $(document).ready(function() {

        {% if not instance %}
            duplicateNameDetect(
                id_first="id_client_first_name",
                id_last="id_client_last_name",
                id_birthdate="id_client_birthdate");
        {% endif %}

    });
</script>
{% endblock %}

templates/accounting/budget_edit.html
<!--

SPDX-License-Identifier: AGPL-3.0-or-later
Copyright (C) 2025 Andrew Knotek <arknotek@pm.me>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

-->


<!DOCTYPE html>
{% extends 'base.html' %}

{% if not popup %}
    {% block breadcrumb %}
        <div class='breadcrumb print-hide'>
            <div class='container'>
                <a href="{% url 'accounting:budget_index' %}">Budget</a>
                {% if instance %}{{instance}}
                {% else %}New Budget
                {%endif%}
            </div>
        </div>
    {% endblock %}
{% endif %}



{% block content %}



<div class='container print-hide'>
    <div class="row">
    	<div class="col-12">
    		<h3>{{ title }}</h3>
            {% if subtitle and not popup %}
            <h5>{{subtitle}}</h5>
            {%endif%}
    		<form id="frm" method="post" action="">
                {% if popup %}<input type='hidden' name='popup' value='true' />{%endif%}
    			{% csrf_token %}
    			{{ form.as_p }}
    			{% include "form_buttons.html" %}
    		</form>
    	</div>
    </div>
</div>

{% if instance %}
<div class="print-show container">
    <h3>{{instance.year}} Budget "{{instance.name}} {{instance.description}}"</h3>
</div>
{% endif %}

{% if instance %}
    {% include 'accounting/budget_item_index.html' %}
{%endif%}

{%endblock%}

templates/accounting/payroll_edit.html
<!--

SPDX-License-Identifier: AGPL-3.0-or-later
Copyright (C) 2025 Andrew Knotek <arknotek@pm.me>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

-->


<!DOCTYPE html>
{% extends 'base.html' %}
{% load nova_tags %}
{% load humanize %}


{% if not popup %}
{% block breadcrumb %}
<div class='breadcrumb print-hide'>
    <div class='container'>
        <a href="{% url 'accounting:payroll_dist_index' %}">Payroll Distribution</a>
        {% if instance %}{{instance}}
        {% else %}New Payroll Distribution
        {%endif%}
    </div>
</div>
{% endblock %}
{% endif %}


{% block content %}



<div class='container{% if popup %}-fluid{%endif%} print-hide'>
    <div class="row">
        <div class="col-lg-6">
            <h3>{{ title }}</h3>
            {% if subtitle and not popup %}
            <h5>{{subtitle}}</h5>
            {%endif%}
            <form id="frm" method="post" action="">
                {% if popup %}<input type='hidden' name='popup' value='true' />{%endif%}
                {% csrf_token %}
                {{ form.as_p }}
                {% include "form_buttons.html" %}
            </form>
        </div>
    </div>
</div>


{% if instance %}
<div class="container">
    <div class="row margin-top-4">
        <div class='col-lg-6'>
            <h4>Employees</h4>
            <table class="listview-table-no-order-no-search">
                <thead>
                    <tr>
                        <th>Last name</th>
                        <th>First name</th>
                        <th>Home cash account</th>
                    </tr>
                </thead>
                {% if employee_data %}
                <tbody>
                    {% for emp in employee_data %}
                    <tr>                        
                        <td><a href="javascript:payrollJe({{instance.id}}, {{emp.id}});" >{{ emp.last_name }}</a></td>
                        <td><a href="javascript:payrollJe({{instance.id}}, {{emp.id}});" >{{ emp.first_name }}</a></td>
                        <td><a href="javascript:payrollJe({{instance.id}}, {{emp.id}});" >{{ emp.home_cash_account }}</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
                {% endif %}
            </table>
        </div>

        <div class='col-lg-6'>
            <h4>Payroll Journal Entries</h4>
            <table class="listview-table-no-order-no-search">
                <thead>
                    <tr>
                        <th>Last name</th>
                        <th>First name</th>
                        <th>Description</th>
                        <th class="right">Amount</th>
                    </tr>
                </thead>
                
                <tbody>
                    {% for entry in entries_data %}
                    <tr>                        
                        <td><a href="/accounting/payroll_je/{{ entry.id }}/" >{{ entry.employee.last_name }}</a></td>
                        <td><a href="/accounting/payroll_je/{{ entry.id }}/" >{{ entry.employee.first_name }}</a></td>
                        <td><a href="/accounting/payroll_je/{{ entry.id }}/" >{{ entry.description }}</a></td>
                        <td><a href="/accounting/payroll_je/{{ entry.id }}/" class="monospace right">{{ entry.get_credit_debit.0|intcomma:2 }}</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
                <tfoot>
                    <td></td>
                    <td></td>
                    <td><span class="cell right"><b>Total: </b></span></td>
                    <td><span class="cell monospace right">{{entries_total|floatformat:2|intcomma}}</span></td>
                </tfoot>
                
            </table>
        </div>
    </div>
</div>

{% endif %}


{%endblock%}