nova/urls.py
"""nova URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
import views

admin.site.site_header = 'NOVA Administration'

handler404 = views.handler404
handler403 = views.handler403
handler500 = views.handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('silk/', include('silk.urls', namespace='silk')),
    re_path(r'^login/', auth_views.LoginView.as_view(), name='login'),
    path('', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logged_out.html', next_page=None), name='logout'),
    path('logged_out/', auth_views.LogoutView.as_view(template_name="logged_out.html", next_page=None), name="logged_out"),
    re_path(r'^loginsort/', views.loginSort, name="Login Sort"),
    re_path(r'^LoginSort/', views.loginSort, name="Login Sort"),  # For some reason our login is leading us to this capitalized re_path. still need to figure out why
    re_path(r'^thanks/', views.thanks, name="Thanks"),

    path('client/', include('client.urls')),
    path('accounting/', include('accounting.urls')),
    path('config/', include('config.urls')),
    path('report/', include('report.urls')),
    path('external/', include('external.urls')),
    path('sacwis/', include('sacwis.urls')),

    #path("script.js", views.script_view, name="script_view"),

    #path("ajax_get_session_time/", views.ajax_get_session_time, name="ajax_get_session_time"),

    path("test500/", views.test500, name="test500"),
    path("testnotify/<str:message>/<int:user_id>/", views.testnotify, name="testnotify"),

    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),

    path("license", TemplateView.as_view(template_name="LICENSE", content_type="text/plain")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

report/urls.py
"""

SPDX-License-Identifier: AGPL-3.0-or-later
Copyright (C) 2025 Andrew Knotek <arknotek@pm.me>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""


from django.views.generic.base import RedirectView
from django.urls import path

from . import views

app_name = 'report'

urlpatterns = [
    path('', views.report_index, name='report_index'),

    # Accounting reports
    path('account_transaction/', views.account_transaction, name='account_transaction'),
    path("ar_ap_county/", views.ar_ap_county, name="ar_ap_county"),
    path("budget/", views.budget_report, name="budget_report"),
    path("dcs_942/", views.dcs_942, name="dcs_942"),
    path('funding_profile/', views.funding_profile_report, name='funding_profile_report'),
    path('transaction/', views.transaction_report, name='transaction_report'),
    path('trial_balance/', views.trial_balance, name='trial_balance'),
    path("doc_search/", views.doc_search, name="doc_search"),

    # Program reports
    path("admission_report/", views.admission_report, name="admission_report"),    
    path("casenote_time/", views.casenote_time, name="casenote_time"),
    path("case_notes/", views.case_notes, name="case_notes"),
    path('client_list/', views.client_list, name='client_list'),
    path("client_statement/", views.client_statement, name="client_statement"), 
    path("current_roster_report/", views.current_roster_report, name="current_roster_report"),   
    path("discharge_report/", views.discharge_report, name="discharge_report"), 
    path("emr_case_note_report/", views.emr_case_note_report, name="emr_case_note_report"),
    path("emr_case_note_report/<int:pk>/", views.emr_case_note_report, name="emr_case_note_report_single"),
    path("emr_case_note_report_my_open/", views.emr_case_note_report_my_open, name="emr_case_note_report_my_open"),
    path("emr_case_note_time/", views.emr_case_note_time, name="emr_case_note_time_report"),
    path("length_of_service_report/", views.length_of_service_report, name="length_of_service_report"),
    # Users say they don't need the doc report, so just have it redirect to
    # the main report view
    #path("doc_report/", views.doc_report, name="doc_report"),
    #path("doc_report/", RedirectView.as_view(url="/report"), name="doc_report"),
    path("pps_crisis_report/", views.pps_crisis_report, name="pps_crisis_report"),
    path("pps_tcm_report/", views.pps_tcm_report, name="pps_tcm_report"),
    path("pps_cst_report/", views.pps_cst_report, name="pps_cst_report"),
    path("program_billing_report/", views.program_billing_report, name="program_billing_report"),
    path("randi_internal_referral_report/", views.randi_internal_referral_report, name="randi_internal_referral_report"),
    path("randi_external_referral_report/", views.randi_external_referral_report, name="randi_external_referral_report"),
    path("clinic_preadmit_report/", views.clinic_preadmit_report, name="clinic_preadmit_report"),
    path("contract_report/", views.contract_report, name="contract_report"),
    path("crisis_data_report/", views.crisis_data_report, name="crisis_data_report"),
    path("time_to_note_report/", views.time_to_note_report, name="time_to_note_report"),

    # This one doesn't need to be registered in report_list.py as it's run
    # right from the emr_form views
    path("emr_form/<int:emr_form_id>/", views.emr_form_report, name="emr_form_report"),

    # *** DO NOT FORGET TO REGISTER YOUR REPORT IN report_list.py! ***

    path("download_as_csv/", views.download_as_csv, name="download_as_csv"),
    path("download_as_pdf/", views.download_as_pdf, name="download_as_pdf"),
    path("cc_report/watcher/", views.cc_report_watcher, name="cc_report_watcher"),
    path("cc_report/watcher_ajax/", views.cc_report_watcher_ajax, name="cc_report_watcher_ajax"),
    path("cc_report/complete/<str:filename>/", views.cc_report, name="cc_report"),
    path("cc_report/clear/", views.cc_report_clear, name="cc_report_clear"),


]

'''
    url(r'^client_list$', views.client_list_view, name='client_list_view'),
    url(r'^TrialBalance$', views.trial_balance_view, name='trial_balance_view'),
    url(r'^AccountTransaction$', views.account_transaction_view, name='account_transaction_view'),
    url(r'^Transaction$', views.transaction_report_view, name='transaction_report_view'),
'''

client/models.py
"""

SPDX-License-Identifier: AGPL-3.0-or-later
Copyright (C) 2025 Andrew Knotek <arknotek@pm.me>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""


import datetime
import json
import re
import uuid
from decimal import Decimal
from dateutil.relativedelta import relativedelta
from dateutil.parser import parse
from django.core.mail import send_mail

import accounting.accounting_choices as ACT_C
import client.client_choices as CLIENT_C
import client.pps_choices as PPS_C

import utils
import pytz

from six import text_type
from annoying.functions import get_object_or_None
from django.core.signing import BadSignature, TimestampSigner, b62_decode
from django.core.exceptions import ValidationError
from django.apps import apps
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Q
from django.utils import timezone
from multiselectfield import MultiSelectField
from django.core import serializers



YES_NO_CHOICES = (
    (None, "----------"),
    ("yes", "Yes"),
    ("no", "No"),
)

YES_NO_UNKNOWN_CHOICES = (
    ("yes", "Yes"),
    ("no", "No"),
    ("unknown", "Unknown"),
)



# Similar first names and last names
class SimFirstName(models.Model):
    value = models.CharField(max_length=255, unique=True, db_index=True)

    def __str__(self):
        return self.value


class SimFirstVar(models.Model):
    name = models.ForeignKey(SimFirstName, related_name="variants", on_delete=models.CASCADE)
    value = models.CharField(max_length=255, db_index=True)

    def __str__(self):
        return f"{self.value} -> {self.name}"




class SimLastName(models.Model):
    value = models.CharField(max_length=255, unique=True, db_index=True)

    def __str__(self):
        return self.value


class SimLastVar(models.Model):
    name = models.ForeignKey(SimLastName, related_name="variants", on_delete=models.CASCADE)
    value = models.CharField(max_length=255, db_index=True)

    def __str__(self):
        return f"{self.value} -> {self.name}"






class EmrMessage(models.Model):
    message = models.TextField()
    expires_at = models.DateTimeField(null=True)
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey("auth.User", null=True, on_delete=models.SET_NULL)



    def __str__(self):
        the_time = datetime.datetime.strftime(self.updated_at, "%m/%d/%Y %H:%M %P")
        return f"Last updated on {the_time} by {self.updated_by.userconfig.full_name}"




class Client(models.Model):
    active = models.BooleanField(default=True)
    title = models.CharField(max_length=1, choices=CLIENT_C.TITLE, default=0)
    first_name = models.CharField(max_length=255, verbose_name="First")
    middle_name = models.CharField(blank=True, null=True, max_length=50, verbose_name="Middle")
    last_name = models.CharField(max_length=255, verbose_name="Last")
    fmt_first_name = models.CharField(max_length=255, null=True, blank=True, db_index=True)
    fmt_last_name = models.CharField(max_length=255, null=True, blank=True, db_index=True)
    alias = models.CharField(max_length=255, null=True, blank=True, verbose_name="Preferred/alias/nickname")
    suffix = models.CharField(max_length=1, choices=CLIENT_C.SUFFIX, default=0)
    birthdate = models.DateField(null=True, blank=True, verbose_name="Birthdate")
    gender = models.CharField(max_length=1, null=True, choices=CLIENT_C.GENDER, verbose_name="Gender at birth", default=0)
    gender_identity = models.CharField(max_length=1, choices=CLIENT_C.GENDER_IDENTITY, verbose_name="Gender identity", default=0)
    race = models.CharField(max_length=255, verbose_name="Race", choices=CLIENT_C.RACE, default=0)
    hispanic = models.CharField(max_length=1, choices=CLIENT_C.HISPANIC, default=0)
    parent_guardian_name = models.CharField(max_length=255, blank=True, null=True, verbose_name="Parent or guardian name")
    assigned_staff = models.ManyToManyField('config.UserConfig', blank=True)
    starting_balance = models.DecimalField(decimal_places=2, max_digits=12, blank=True, null=True)
    legacy_client_number = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=255, null=True, blank=True)
    phone_ext = models.CharField(max_length=255, null=True, blank=True, verbose_name="ext")
    alt_phone = models.CharField(max_length=255, null=True, blank=True)
    alt_phone_ext = models.CharField(max_length=255, null=True, blank=True, verbose_name="ext")
    email = models.EmailField(max_length=255, null=True, blank=True)
    # Add other id numbers as they are needed.
    ssn = models.CharField(max_length=255, null=True, blank=True, verbose_name="SSN")


    def save(self, *args, **kwargs):
        # Saving formatted copies of the first and last name to make the
        # duplicate name detection logically simpler and more performant
        # This just removes any non-alphanumeric characters for the first
        # and last names and saves them into their respective fmt_ fields
        self.fmt_first_name = re.sub(r'\W+', '', self.first_name)
        self.fmt_last_name = re.sub(r'\W+', '', self.last_name)
        super().save(*args, **kwargs)


    def __str__(self):
        # Format a string with the first and alias if there is an alias
        if self.alias:
            firstname = f'{self.first_name} "{self.alias}"'
        else:
            firstname = self.first_name


        if self.birthdate is None:
            return f"{self.last_name}, {firstname} - ({self.id})"
        else:

            dob = self.birthdate.strftime(settings.HUMAN_DATE_FORMAT)
            return f"{self.last_name}, {firstname} ({self.id}) - {dob} ({self.get_age()})"


    def name(self):
        # Format a string with the first and alias if there is an alias
        if self.alias:
            firstname = f'{self.first_name} "{self.alias}"'
        else:
            firstname = self.first_name

        return self.last_name + ", " + firstname


    def name_first_last(self):
        return "{} {}".format(self.first_name, self.last_name)





    def get_age(self):
        today = timezone.now().date()
        age = relativedelta(today, self.birthdate)

        if age.years == 0 and age.months < 1:
            return f"{age.days} day{'s' if age.days > 1 else ''}"

        if age.years < 2:
            total_months = (age.years * 12) + age.months
            return f"{total_months} month{'s' if total_months > 1 else ''}"

        return f"{age.years} year{'s' if age.years > 1 else ''}"





    def get_address(self):
        found_address = Address.objects.filter(client=self, is_physical=True, active=True).first()
        if found_address:
            return found_address

        found_address = Address.objects.filter(client=self, is_mailing=True, active=True).first()
        if found_address:
            return found_address

        found_address = Address.objects.filter(client=self, is_billing=True, active=True).first()
        if found_address:
            return found_address

        found_address = Address.objects.filter(client=self, active=True).first()
        if found_address:
            return found_address


        # Nothing found.
        return None




    def get_addresses(self):
        return Address.objects.filter(client=self).order_by('-active')



    def get_billing_address(self):
        # name
        # care of (if exists)
        # street 1  + Apt/Suite
        # City State Zip
        address_results = Address.objects.filter(
            client=self, is_billing=True)

        if len(address_results) == 0:
            return ""

        address = address_results[0]

        if address.care_of:
            fmt = "{}<br>{}<br>{} {}<br>{} {} {}".format(
                self.name_first_last(), address.care_of, address.street,
                address.apt, address.city, address.state, address.zip)
        else:
            fmt = "{}<br>{} {}<br>{} {} {}".format(
                self.name_first_last(), address.street, address.apt,
                address.city, address.state, address.zip)

        return fmt


    def get_insurance_info(self):
        insurance_items = self.insurance_set.all().order_by("-id")

        if len(insurance_items) == 0:
            return ""
        elif len(insurance_items) == 1:
            return str(insurance_items[0])
        else:
            return "\n".join([str(x) for x in insurance_items])


    def get_insurance_info_html(self):
        return self.get_insurance_info().replace("\n", "<br>")

    def get_open_episodes(self):
        open_episodes = EmrEpisode.objects.filter(client=self, end__isnull=True)
        return open_episodes


    def get_auto_name(self):
        return str(self)



class PastLegalName(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    title = models.CharField(max_length=1, choices=CLIENT_C.TITLE, default=0)
    first_name = models.CharField(max_length=50, verbose_name="First")
    middle_name = models.CharField(blank=True, max_length=50, verbose_name="Middle")
    last_name = models.CharField(max_length=50, verbose_name="Last")
    suffix = models.CharField(max_length=1, choices=CLIENT_C.SUFFIX, default=0)
    date_changed = models.DateField(auto_now_add=True)




class Address(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)

templates/report/emr_report_forms/crisis_case_note.html
<!--

SPDX-License-Identifier: AGPL-3.0-or-later
Copyright (C) 2025 Andrew Knotek <arknotek@pm.me>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

-->


{% load nova_tags %}

<p class="w33">
    <span>Date</span>{{ instance.date|date:'m/d/Y' }}
</p>
<p class="w33">
    <span>Creator</span>{{ instance.created_by.userconfig.full_name}}
</p>


<div class="form-section">
    <p class="w100">
        <span>Credentials</span>{{instance.get_credentials_display}}
    </p>

    <p class="w100">
        <span>Diagnosis</span>{{instance.diagnosis}}
    </p>

    <p class="w100">
        <span>Place of service</span>{{instance.get_place_of_service_display}}
    </p>

    <p class="w25">
        <span>Service start</span>{{instance.service_start|date:'H:i'}}
    </p>

    <p class="w25">
        <span>Service end</span>{{instance.service_end|date:'H:i'}}
    </p>

    <p class="w25 clear-left">
        <span>Service minutes</span>{{instance.service_minutes|default:'0'}}
    </p>

    <p class="w25">
        <span>Travel minutes</span>{{instance.travel_minutes|default:'0'}}
    </p>

    <p class="w25">
        <span>Doc minutes</span>{{instance.doc_minutes|default:'0'}}
    </p>

    <p class="w25">
        <span>Total minutes</span>{{instance.total_minutes|default:'0'}}
    </p>

    <p class="w25">
        <span>Billing code</span>{{instance.billing_code}}
    </p>

    <p class="w25">
        <span>Units</span>{{instance.units}}
    </p>

    <p class="w100">
        <span>Note</span>{{instance.note|linebreaksbr|safe}}
    </p>


</div>



<div class="form-section">
    <h4>Linked Docs</h4>
    <hr>
    <p class="w100">
        <span>Linked docs</span>{{ instance.get_linked_docs|safe }}
    </p>
</div>

templates/report/emr_report_forms/cst_pps_mh_discharge.html
<!--

SPDX-License-Identifier: AGPL-3.0-or-later
Copyright (C) 2025 Andrew Knotek <arknotek@pm.me>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

-->


{% load nova_tags %}
<p class="w33">
    <span>Creator</span>{{ instance.created_by.userconfig.full_name}}
</p>

<div class="form-section">
    <h4>Demographic Information</h4>
    <hr>

    <p class="w100">
        <span>First name</span>{{instance.emrepisode.client.first_name}}
    </p>

    <p class="w100">
        <span>Last name</span>{{instance.emrepisode.client.last_name}}
    </p>

    <p class="w100">
        <span>DOB</span>{{instance.emrepisode.client.birthdate|date:'m/d/Y'}}
    </p>

    <p class="w100">
        <span>Gender</span>{{instance.emrepisode.client.get_gender_display}}
    </p>

    <p class="w100">
        <span>Address</span>{{instance.emrepisode.client.get_address.get_long_address}}
    </p>

    <p class="w100">
        <span>Phone</span>{{instance.emrepisode.client.phone}}{{instance.emrepisode.client.phone_ext|ext}}
    </p>

    <p class="w100">
        <span>Race</span>{{instance.emrepisode.client.get_race_display}}
    </p>

    <p class="w100">
        <span>Ethnicity</span>{{instance.emrepisode.client.get_hispanic_display}}
    </p>
</div>


<div class="form-section">
    <h4>Consumer Status Report</h4>
    <hr>

    <p class="w100">
        <span>Status time frame</span>Discharge
    </p>

    <p class="w100">
        <span>Service</span>{{instance.service}}
    </p>

    <p class="w100">
        <span>Commitment status</span>{{instance.get_commit_stat_display}}
    </p>

    <p class="w100">
        <span>Employment status</span>{{instance.get_employ_stat_display}}
    </p>

    <p class="w100">
        <span>Living arrangement</span>{{instance.get_living_stat_display}}
    </p>
</div>


<div class="form-section">
    <h5>Criminal Justice System Involvement</h5>

    <p class="w100">
        <span>None</span>{{instance.cjs_none|chk}}
    </p>

    <p class="w100">
        <span>On probation</span>{{instance.cjs_probation|chk}}
    </p>

    <p class="w100">
        <span>Arrests</span>{{instance.cjs_arrests|chk}}
    </p>

    <p class="w100">
        <span>Jail</span>{{instance.cjs_jail|chk}}
    </p>

    <p class="w100">
        <span>On parole</span>{{instance.cjs_parole|chk}}
    </p>

    <p class="w100">
        <span>Juvenile justice system contact</span>{{instance.cjs_juv|chk}}
    </p>

    <p class="w100">
        <span>Unknown</span>{{instance.cjs_unknown|chk}}
    </p>

    <p class="w100">
        <span>Number of arrests in the past 30 days</span>{{instance.num_arrests}}
    </p>

    <p class="w100">
        <span>Number of arrests in the past 6 months</span>{{instance.num_arrests_sixmonths}}
    </p>
</div>

<div class="form-section">
    <h4>Closing PPS Information</h4>
    <hr>

    <p class="w100">
        <span>End date</span>{{instance.end_date|list_date}}
    </p>

    <p class="w100">
        <span>SPC end reason</span>{{instance.get_pps_mh_spc_end_reason_display}}
    </p>
</div>

templates/report/emr_report_forms/tcm_pps_aoda_admission.html
<!--

SPDX-License-Identifier: AGPL-3.0-or-later
Copyright (C) 2025 Andrew Knotek <arknotek@pm.me>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

-->


{% load nova_tags %}
<p class="w33">
    <span>Creator</span>{{ instance.created_by.userconfig.full_name}}
</p>


<div class="form-section">
    <h4>Demographic Information</h4>
    <hr>

    <p class="w100">
        <span>First name</span>{{instance.emrepisode.client.first_name}}
    </p>

    <p class="w100">
        <span>Last name</span>{{instance.emrepisode.client.last_name}}
    </p>

    <p class="w100">
        <span>DOB</span>{{instance.emrepisode.client.birthdate|date:'m/d/Y'}}
    </p>

    <p class="w100">
        <span>Gender</span>{{instance.emrepisode.client.get_gender_display}}
    </p>

    <p class="w100">
        <span>Address</span>{{instance.emrepisode.client.get_address.get_long_address}}
    </p>

    <p class="w100">
        <span>Phone</span>{{instance.emrepisode.client.phone}}{{instance.emrepisode.client.phone_ext|ext}}
    </p>

    <p class="w100">
        <span>Race</span>{{instance.emrepisode.client.get_race_display}}
    </p>

    <p class="w100">
        <span>Ethnicity</span>{{instance.emrepisode.client.get_hispanic_display}}
    </p>

    <p class="w100">
        <span>County of residence</span>{{instance.get_county_of_residence_display|default:''}}
    </p>

    <p class="w100">
        <span>SPC start date</span>{{ instance.get_spc_start_date|list_date}}
    </p>
</div>


<div class="form-section">
    <h4>Admission Information</h4>
    <hr>

    <p class="w100">
        <span>Service</span>{{instance.service}}
    </p>

    <p class="w100">
        <span>Brief service</span>{{instance.get_brief_service_display}}
    </p>

    <p class="w100">
        <span>Agency of responsibility</span>{{instance.agency_of_resp}}
    </p>

    <p class="w100">
        <span>Provider WPI/NPI</span>{{instance.provider_wpi_npi}}
    </p>

    <p class="w100">
        <span>Referral source</span>{{instance.get_referral_source_display}}
    </p>

    <p class="w100">
        <span>Co-dependent/collateral</span>{{instance.get_cd_collat_display}}
    </p>

    <p class="w100">
        <span>Education</span>{{instance.get_education_display}}
    </p>

    <p class="w100">
        <span>Number of arrests in the past 30 days</span>{{instance.num_arrests}}
    </p>

    <p class="w100">
        <span>Employment status</span>{{instance.get_employ_stat_display}}
    </p>

    <p class="w100">
        <span>Living arrangement</span>{{instance.get_living_stat_display}}
    </p>

    <p class="w100">
        <span>Support group attendance</span>{{instance.get_group_attend_display}}
    </p>

    <p class="w100">
        <span>Pregnant</span>{{instance.get_pregnant_display}}
    </p>

    <p class="w100">
        <span>Primary substance use problem</span>{{instance.get_substance_problem1_display}}
    </p>

    {% if instance.substance_problem1 %}
        <p class="w100 ml-4">
            <span>Usual route of administration</span>{{instance.get_route_admin1_display}}
        </p>

        <p class="w100 ml-4">
            <span>Use frequency</span>{{instance.get_use_freq1_display}}
        </p>

        <p class="w100 ml-4">
            <span>Age at first use</span>{{instance.age_first_use1}}
        </p>
    {% endif %}



    {% if instance.substance_problem2 %}
        <p class="w100">
            <span>Secondary substance use problem</span>{{instance.get_substance_problem2_display}}
        </p>

        <p class="w100 ml-4">
            <span>Usual route of administration</span>{{instance.get_route_admin2_display}}
        </p>

        <p class="w100 ml-4">
            <span>Use frequency</span>{{instance.get_use_freq2_display}}
        </p>

        <p class="w100 ml-4">
            <span>Age at first use</span>{{instance.age_first_use2}}
        </p>
    {% endif %}

    {% if instance.substance_problem3 %}
        <p class="w100">
            <span>Tertiary substance use problem</span>{{instance.get_substance_problem3_display}}
        </p>

        <p class="w100 ml-4">
            <span>Usual route of administration</span>{{instance.get_route_admin3_display}}
        </p>

        <p class="w100 ml-4">
            <span>Use frequency</span>{{instance.get_use_freq3_display}}
        </p>

        <p class="w100 ml-4">
            <span>Age at first use</span>{{instance.age_first_use3}}
        </p>
    {% endif %}
</div>