client/urls.py
"""

SPDX-License-Identifier: AGPL-3.0-or-later
Copyright (C) 2025 Andrew Knotek <arknotek@pm.me>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""


from django.urls import path

from . import views

app_name = 'client'

urlpatterns = [
    path('all/', views.client_index, name="client_index"),
    path('inactive/', views.client_inactive, name='client_inactive'),
    path('me/', views.me_index, name='me_index'),
    path('<int:client_id>/', views.client_edit, name='client_edit'),
    path('new/', views.client_edit, name='client_new'),

    path("caseworker_login/", views.caseworker_login, name="caseworker_login"),

    path("set_active/<int:client_id>/", views.client_set_active, name="client_set_active"),
    path("set_inactive/<int:client_id>/", views.client_set_inactive, name="client_set_inactive"),

    # These are the tab menu items on the client screen
    path("client_settings/<int:client_id>/", views.client_settings_index, name="client_settings_index"),

    path("emr_episodes/<int:client_id>/", views.emr_episode_edit, name="emr_episodes_index"),
    path("emr_episodes/<int:client_id>/<int:episode_id>/", views.emr_episode_edit, name="emr_episodes_edit"),
    # Build an EMR Episode view where only the episode is ID (it can redirect to the one above here)

    path("emr_episodes/<int:client_id>/<int:episode_id>/form/<int:form_type_id>/", views.emr_episode_edit, name="emr_episode_form_list"),
    path("emr_episodes/<int:client_id>/<int:episode_id>/form/<str:note_type_id>/", views.emr_episode_edit, name="emr_episode_note_list"),
    path("emr_episodes/<int:client_id>/<int:episode_id>/doc/<int:doc_type_id>/", views.emr_episode_edit, name="emr_episode_doc_list"),

    path("new_emr_episode/<str:episode_type>/<int:client_id>/", views.new_emr_episode, name="new_emr_episode"),

    path("emr_form/<int:form_type_id>/<int:episode_id>/", views.emr_form_edit, name="emr_form_new"),
    path("emr_form/<int:emr_form_id>/", views.emr_form_edit, name="emr_form_edit"),
    path("emr_form/<int:emr_form_id>/sign/", views.emr_form_sign, name="emr_form_sign"),
    path("emr_form/<int:emr_form_id>/unlock/", views.emr_form_unlock, name="emr_form_sign"),
    path("emr_form_history/<int:emr_form_id>/", views.emr_form_history, name="emr_form_history"),

    path("emr_form/<int:emr_form_id>/supervisor_sign/", views.emr_form_supervisor_sign, name="emr_form_supervisor_sign"),
    path("emr_form/<int:emr_form_id>/electronic_signature/", views.emrform_electric_sig, name="emr_form_electronic_sig_new"),
    path("emr_form/<int:emr_form_id>/electronic_signature/<int:emrform_sig_id>/", views.emrform_electric_sig, name="emr_form_electronic_sig_edit"),

    path("emr_doc/<int:doc_type_id>/<int:episode_id>/", views.emr_doc_edit, name="emr_doc_new"),
    path("emr_doc/<int:emr_doc_id>/", views.emr_doc_edit, name="emr_doc_edit"),
    path("emr_doc/<int:emr_doc_id>/emr_docs/<int:emr_doc_id2>/<str:filename>", views.emr_doc_file, name="emr_doc_file"),
    path("emr_doc/<int:emr_doc_id>/emr_docs/<int:emr_doc_id2>/<str:filename>/", views.emr_doc_file, name="emr_doc_file"),
    path("emr_doc/<int:emr_doc_id>/file/", views.emr_doc_file, name="emr_doc_file_short"),
    path("emr_doc/<int:emr_doc_id>/view/", views.emr_doc_view, name="emr_doc_view"),
    path("emr_doc/<int:emr_doc_id>/<int:emr_form_id>/unlink/", views.emr_doc_unlink, name="emr_doc_unlink"),

    path("emr_casenote/reopen/<int:emr_casenote_id>/", views.emr_casenote_reopen, name="emr_casenote_reopen"),

    path("emr_message/", views.emr_message_edit, name="emr_message_new"),
    path("emr_message/<int:message_id>/", views.emr_message_edit, name="emr_message_edit"),

    path("pps_episodes/<int:client_id>/", views.pps_episodes_index, name="pps_episodes_index"),
    path("case_notes_index/<int:client_id>/", views.case_notes_index, name="case_notes"),
    path("state_forms/<int:client_id>/", views.state_forms_index, name="state_forms_index"),

    path('address/<int:address_id>/', views.address_edit, name="address_edit"),
    path('address/new/', views.address_edit, name="address_new"),

    path('contact/<int:contact_id>/', views.contact_edit, name="contact_edit"),
    path('contact/new/', views.contact_edit, name="contact_new"),

    path('insurance/<int:insurance_id>/', views.insurance_edit, name="insurance_edit"),
    path('insurance/', views.insurance_edit, name="insurance_new"),

    path('assigned_staff/<int:assigned_staff_id>/', views.assigned_staff_edit, name='assigned_staff_edit'),
    path('assigned_staff/', views.assigned_staff_edit, name='assigned_staff_new'),

    path('casenote/<int:casenote_id>/', views.casenote_edit, name="casenote_edit"),
    path('casenote/new/', views.casenote_edit, name="casenote_new"),

    path("casenote_file/<int:file_id>/casenote_files/<int:user_id>/<int:client_id>/<str:filename>", views.casenote_files),
    path("casenote_file/<int:file_id>/casenote_files/<int:user_id>/<int:client_id>/<str:filename>/", views.casenote_files),
    path('casenote_file/<int:casenote_file_id>/', views.casenote_file, name='casenote_file'),
    path('casenote_file/new/', views.casenote_file, name='casenote_file_new'),

    path("casenote/view_all/<int:client_id>/", views.casenote_view_all, name="casenote_view_all"),

    path("casenote/reopen/<int:casenote_id>/", views.casenote_reopen, name="casenote_reopen"),

    path("legal_name/<int:client_id>/<int:legal_name_id>/", views.legal_name_edit, name="legal_name"),
    path("legal_name/<int:client_id>/new/", views.legal_name_edit, name="legal_name_new"),


    path("sacwis/import_mgmt/", views.sacwis_import_mgmt, name="sacwis_import_mgmt"),
    path("sacwis/import_mgmt/<int:sac_row_id>/", views.sacwis_import_edit, name="sacwis_import_edit"),

    # The PPS episodes are not currently in use
    #path("pps_epi_sort/<uuid>/", views.pps_epi_sort, name="pps_epi_sort"),

    #path('pps_aoda_epi/<int:pk>/', views.pps_aoda_edit, name='pps_aoda_epi_edit'),
    #path('pps_aoda_epi/new/', views.pps_aoda_edit, name='pps_aoda_epi_new'),

    #path('pps_mh_epi/<int:pk>/', views.pps_mh_edit, name='pps_mh_epi_edit'),
    #path('pps_mh_epi/new/', views.pps_mh_edit, name='pps_mh_epi_new'),

    #path('pps_core_epi/<int:pk>/', views.pps_core_edit, name='pps_core_epi_edit'),
    #path('pps_core_epi/new/', views.pps_core_edit, name='pps_mh_core_epi_new'),

    #path('pps_b3_epi/<int:pk>/', views.pps_b3_edit, name='pps_b3_epi_edit'),
    #path('pps_b3_epi/new/', views.pps_b3_edit, name='pps_mh_b3_epi_new'),


    path("atp/<int:pk>/", views.atp_edit, name="atp_edit"),
    path("atp/new/", views.atp_edit, name="atp_new"),



    path('form/<name>/', views.form_download, name='form_download'),

    path("ajax_duplicate_name_detect/", views.ajax_duplicate_name_detect, name="duplicate_name_detect"),
    path("ajax_calculate_units/<int:emr_form_id>/<int:minutes>/", views.ajax_calculate_units, name="ajax_calculate_minutes"),



]

nova/urls.py
"""nova URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
import views

admin.site.site_header = 'NOVA Administration'

handler404 = views.handler404
handler403 = views.handler403
handler500 = views.handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('silk/', include('silk.urls', namespace='silk')),
    re_path(r'^login/', auth_views.LoginView.as_view(), name='login'),
    path('', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logged_out.html', next_page=None), name='logout'),
    path('logged_out/', auth_views.LogoutView.as_view(template_name="logged_out.html", next_page=None), name="logged_out"),
    re_path(r'^loginsort/', views.loginSort, name="Login Sort"),
    re_path(r'^LoginSort/', views.loginSort, name="Login Sort"),  # For some reason our login is leading us to this capitalized re_path. still need to figure out why
    re_path(r'^thanks/', views.thanks, name="Thanks"),

    path('client/', include('client.urls')),
    path('accounting/', include('accounting.urls')),
    path('config/', include('config.urls')),
    path('report/', include('report.urls')),
    path('external/', include('external.urls')),
    path('sacwis/', include('sacwis.urls')),

    #path("script.js", views.script_view, name="script_view"),

    #path("ajax_get_session_time/", views.ajax_get_session_time, name="ajax_get_session_time"),

    path("test500/", views.test500, name="test500"),
    path("testnotify/<str:message>/<int:user_id>/", views.testnotify, name="testnotify"),

    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),

    path("license", TemplateView.as_view(template_name="LICENSE", content_type="text/plain")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/client/case_notes_index.html
<!--

SPDX-License-Identifier: AGPL-3.0-or-later
Copyright (C) 2025 Andrew Knotek <arknotek@pm.me>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

-->


{% extends 'base.html' %}

{% block breadcrumb %}
<div class='breadcrumb'>
    <div class='container'>
        <a href="{% url 'client:client_index' %}">All Clients</a>
        <a href="{% url 'client:me_index' %}">My Clients</a>
            {{client.name}} ({{client.id}}){% if client.active is False %} (Inactive){% endif %}
    </div>
</div>
{% endblock %}


{% block content %}




{% include 'client/client_ribbon.html' %}

{% include 'client/casenote_index.html' %}

{% endblock %}

templates/client/casenote_view_all.html
<!--

SPDX-License-Identifier: AGPL-3.0-or-later
Copyright (C) 2025 Andrew Knotek <arknotek@pm.me>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

-->


<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}
<div class='container'>

<div class='row margin-top-2'>
    <div class="col-md-12">
        <h4>{{title}}</h4>
    </div>
</div>


{% for note in notes %}
<div class="row margin-top-1">
    <div class='col-12'>
        <p class="bold">
            {{note.date|date:'m/d/Y'}}<br>
            {{note.hours}} hours {{note.minutes}} minutes            
        </p>
        <p>
            {% if note.note %}
            {{ note.note|safe }}
            {% else %}
            No text to display
            {% endif %}
        </p>
    </div>
</div>
{% endfor %}

</div>
{%endblock%} 

templates/client/client_edit.html
<!--

SPDX-License-Identifier: AGPL-3.0-or-later
Copyright (C) 2025 Andrew Knotek <arknotek@pm.me>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

-->


<!DOCTYPE html>
{% extends 'base.html' %}



{% block breadcrumb %}
<div class='breadcrumb'>
    <div class='container'>
        <a href="{% url 'client:client_index' %}">All Clients</a>
        <a href="{% url 'client:me_index' %}">My Clients</a>
        {% if instance %}{{instance}}{% if client.active is False %} (Inactive){% endif %}
        {%else%}New Client
        {%endif%}
    </div>
</div>
{% endblock %}


{% block content %}



{% if instance %}
    {% include 'client/client_ribbon.html' %}
{% endif %}

<div class='container'>
    <div class="row">
        <div class='col-lg-12'>
            <div class='row'>
            	<div class="col-12">
                    {% if not instance %}
            		<h2>{{ title }}</h2>
                    {% endif %}
                    <!--<h4>{{subtitle}}</h4>-->
            		<form id="frm" method="post" action="">
                        {% if popup %}<input type='hidden' name='popup' value='true' />{%endif%}
            			{% csrf_token %}
            			{{ form.as_p }}

            			{% include "form_buttons.html" %}
            		</form>
            	</div>
            </div>
        </div>



        {% if instance.pastlegalname_set.all|length > 0 %}
            <div class="col-md-6 margin-top-2">
                {% if instance.pastlegalname_set.all|length > 1 %}
                        <h4>Past Legal Names</h4>
                {% else %}
                        <h4>Past Legal Name</h4>
                {% endif %}
                <table class="listview-table-no-order-no-search">
                    <thead>
                        <tr>
                            <th>Last</th>
                            <th>First</th>
                            <th>Middle</th>
                            <th>Date Changed</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for item in instance.pastlegalname_set.all %}
                        <tr>
                            <td><a href="/client/client_settings/{{instance.id}}">{{ item.last_name }}</a></td>
                            <td><a href="/client/client_settings/{{instance.id}}">{{ item.first_name }}</a></td>
                            <td><a href="/client/client_settings/{{instance.id}}">{{ item.middle_name }}</a></td>
                            <td><a href="/client/client_settings/{{instance.id}}">{{ item.date_changed|date:'m/d/Y' }}</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>

                </table>
            </div>
        {% endif %}
    </div>
</div>

<div class="container">
    <div class="row mt-4">
        <div class='col-lg-12 margin-top-4'>

            {% if instance %}
                {% include 'client/address_index.html' %}
                {% include 'client/contact_index.html' %}
                {% include 'client/insurance_index.html' %}
            {%endif%}
        </div>
    </div>
</div>

{% if request.user.userconfig.notes_under_demo %}
<div class='container'>
    <div class='row margin-top-4'>
        <div class="col-md-12">
            {% if client %}
            <h3>B-3 Case Notes
                <a class="btn btn-sm btn-secondary ml-4 exclude-edit-false" href="/client/casenote/new/?client={{client.id}}">
                    Create Case Note
                </a>

                <a class="btn btn-sm btn-secondary ml-4 exclude-edit-false" href="/client/casenote/view_all/{{client.id}}/">
                    View All Case Notes for {{client.name}}
                </a>
            </h3>
            {%else%}
            <h4>Recent Case Notes</h4>
            {%endif%}
        </div>
    </div>
</div>

<div class='container'>
    <div class="row margin-top-1">
        <div class='col-12'>
            <table class="listview-table-no-order-no-search">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Time</th>
                        <th>Caseworker</th>
                        {% if not client %}<th>Client</th>{%endif%}
                        <th>Service</th>
                        <th>Diagnosis</th>
                    </tr>
                </thead>
                {% if casenote_data %}
                <tbody>
                    {% for item in casenote_data %}
                    <tr>
                        <td class='nowrap'><a class='monospace active-{{item.is_open}}' href="/client/casenote/{{ item.id }}/"><span class='d-none'>{{ item.date | date:'Ymd' }}</span>{{ item.date | date:'m/d/Y' }}</a></td>
                        <td class='nowrap'><a class='monospace active-{{item.is_open}}' href="/client/casenote/{{ item.id }}/">{{item.get_time}}</a></td>
                        <td><a class='active-{{item.is_open}}' href="/client/casenote/{{ item.id }}/">{{ item.get_signer_user }}</a></td>
   {% if not client %}<td><a class='active-{{item.is_open}}' href="/client/casenote/{{ item.id }}/">{{ item.client }}</a></td>{%endif%}
                        <td><a class='active-{{item.is_open}}' href="/client/casenote/{{ item.id }}/">{% if item.is_open is False %}[Closed] {%endif%}{{ item.service }}</a></td>
                        <td><a class='active-{{item.is_open}}' href="/client/casenote/{{ item.id }}/">{{ item.diagnosis }}</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
                {% endif %}
            </table>
        </div>
    </div>
</div>
{% endif %}


{%endblock%}

{% block page_javascript %}
<script>
    $(document).ready(function() {

        {% if not instance %}
            duplicateNameDetect(
                id_first="id_first_name",
                id_last="id_last_name",
                id_birthdate="id_birthdate");
        {% endif %}

    });

    // We want to be able to keep the client face-sheet screen in edit-mode
    // until the user navigates away from it. People want to be able to make
    // changes to the client's address, contacts, and insurance without having
    // to keep re-enabling edit mode.
    var editSticky = window.localStorage.getItem("editSticky");

    if (editSticky == "true") {
        $("#btn-return").click(function() {
            window.localStorage.removeItem("editSticky");
        });

        $("input[name='delete']").click(function() {
            window.localStorage.removeItem("editSticky");
        });

        $("a").click(function() {
            // want to remove editSticky from local storage if the user is
            // navigating away from the facesheet. In this case any link
            // that is not the client, address, contact or insurance views
            var url = $(this).attr("href");
            var stayUrls = ["/client/address/", "/client/contact", "/client/insurance/"];
            var needsClearing = true;
            for (var item in stayUrls) {
                if (url.includes(stayUrls[item])) {
                    needsClearing = false;
                    break;
                }
            }

            if (needsClearing === true) {
                window.localStorage.removeItem("editSticky");
            }
        });
    }



    if (editSticky != "true" && getUrl("edit") != "true" && window.location.pathname != "/client/new/") {
        renderNoEdit();
        $("#ribbon-item-facesheet").attr("href", "?edit=true");

        $("#ribbon-item-facesheet").click(function() {
            window.localStorage.setItem("editSticky", "true");
        });
    }

    {% if request.user.userconfig.user_type == '4' %}
        /*
            Always want no edit for the auditors. Even though they cannot make
            any changes or press the save button, there's no reason these
            fields should be visible for them
        */
        renderNoEdit();
    {% endif %}

    function showInactiveAddresses() {
        $("#btn-show-inactive-addresses").fadeOut();
        $(".inactive-address").each(function() {
            $(this).fadeIn();
        });
    }


</script>

{% endblock %}

templates/client/client_settings.html
<!--

SPDX-License-Identifier: AGPL-3.0-or-later
Copyright (C) 2025 Andrew Knotek <arknotek@pm.me>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

-->


{% extends 'base.html' %}

{% block breadcrumb %}
<div class='breadcrumb'>
    <div class='container'>
        <a href="{% url 'client:client_index' %}">All Clients</a>
        <a href="{% url 'client:me_index' %}">My Clients</a>
            {{client.name}} ({{client.id}}){% if client.active is False %} (Inactive){% endif %}
    </div>
</div>
{% endblock %}



{% block content %}



{% include 'client/client_ribbon.html' %}


<div class="container">
    <div class="row">
        <div class="col-xl-6">
            <div class="row margin-top-2">
                <div class="col-12">
                    <h3>{{client.name}} is
                        {% if client.active %}
                        <u>Active</u>
                        {% else %}
                        <u>Inactive</u>
                        {% endif %}
                        </h3>

                        

                        {% if client.active %}

                            {% if client.get_open_episodes %}
                                <p>This client has open episodes and cannot be set to inactive.</p>
                            {% else %}
                                <a class="btn btn-sm btn-secondary btn-delete ml-4 margin-top-1" href="/client/set_inactive/{{ client.id }}/">
                                    Set Client to Inactive
                                </a>
                            {% endif %}


                        {% else %}
                            <a class="btn btn-sm btn-secondary ml-4 margin-top-1" href="/client/set_active/{{ client.id }}/">
                                Set Client to Active
                            </a>

                        {% endif %} 
                        

                </div>
            </div>
        </div>
        <div class="col-xl-6">
            {% include 'client/assignedstaff_index.html' %}
        </div>

        <div class="col-xl-6">
            {% include 'client/atp_index.html' %}
        </div>

        <div class="col-xl-6">
            {% include 'client/legal_name_index.html' %}
        </div>
    </div>
    
</div>

{% endblock %}

templates/client/emr_doc_edit.html
<!--

SPDX-License-Identifier: AGPL-3.0-or-later
Copyright (C) 2025 Andrew Knotek <arknotek@pm.me>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

-->


<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}

{% if not popup %}
<div class='breadcrumb'>
    <div class='container'>
        <a href="{% url 'client:client_index' %}">All Clients</a>
        <a href="{% url 'client:me_index' %}">My Clients</a>
        <a href="/client/{{episode.client.id}}/">{{episode.client}}</a>
        <a href="/client/emr_episodes/{{episode.client.id}}/{{episode.id}}/">{{episode.get_episode_type_display}}</a>
        <a href="/client/emr_episodes/{{episode.client.id}}/{{episode.id}}/fov/{{instance.emrdoctype.id}}/">{{instance.emrdoctype.name}} Docs</a>        
        {% if instance %}
            {% if instance.id is None %}New {% endif %}{{instance.emrdoctype.name}}
        {% endif %}
    </div>
</div>
{% endif %}

<div class='container{% if popup%}-fluid{%endif%}'>
<div class="row">
    <div class="col-12">
        <h3>{{ title }}</h3>
        {% if subtitle and not popup %}
        <h5>{{subtitle}}</h5>
        {%endif%}
        <form id="frm" method="post" action="" enctype="multipart/form-data">
            {% if popup %}<input type='hidden' name='popup' value='true' />{%endif%}
            {% csrf_token %}
            {{ form.as_p }}

            {% if instance.id %}
                <p class="w100" style="float:left; padding: 0 0.25rem;">
                    {% include "shared_link_interface.html" %}
                    {% if request.user.userconfig.view_only is False  %}
                        <a href="/external/sharedlink/create/client/emrdoc/{{instance.id}}/" style="display:block; padding:0 0.25rem; margin-top:0.25rem;">
                            Generate new link
                        </a>

                        <a href="/external/sharedlink/manage/" target="_parent" style="display:block; padding:0 0.25rem; margin-top:0.25rem;">
                            Manage links
                        </a>
                    {% endif %}
                </p>
            {% endif %}

            {% include "form_buttons.html" %}
        </form>
    </div>
</div>
</div>
{%endblock%}

templates/client/ppsepi_edit.html
<!--

SPDX-License-Identifier: AGPL-3.0-or-later
Copyright (C) 2025 Andrew Knotek <arknotek@pm.me>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

-->


<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}



<div class='breadcrumb'>
    <div class='container'>
        <a href="{% url 'client:client_index' %}">All Clients</a>
        <a href="{% url 'client:me_index' %}">My Clients</a>
        {% if instance %}
        <a href="/client/{{instance.client.id}}/">{{instance.client.name}}</a>
        {{instance.get_name}}
        {%endif%}
    </div>
</div>



<div class='container{% if popup%}-fluid{%endif%}'>
    <div class="row">
    	<div class="col-12">
    		<h3>{{ title }}</h3>
    		<form id="frm" method="post" action="">
                {% if popup %}<input type='hidden' name='popup' value='true' />{%endif%}
    			{% csrf_token %}
    			{{ form.as_p }}
    			{% include "form_buttons.html" %}
    		</form>
    	</div>
    </div>
</div>

{% if instance and instance.id %}
    <!-- List services performed under this episode -->
    {% include 'client/ppssrv_index.html' %}
{% endif %}

{%endblock%}

{% block page_javascript %}
<script>
//$("#id_criminal_interactions").prev().addClass("criminal-interactions-after");
</script>
{% endblock %}